[settings]
idiomatic_version_file_enable_tools = []

[tools]
node = "22.16.0"

[tasks.install]
run = "npm install"
sources = ["package.json", "package-lock.json"]
outputs.auto = true

[tasks.build]
run = "npx quartz build -d .."
depends = "install"

[tasks.serve]
run = "npx quartz build -d .. --serve"
depends = "install"
