[settings]
idiomatic_version_file_enable_tools = []

[tools]
node = "22.16.0"
"npm:wrangler" = "latest"
"npm:obsidian-headless" = "latest"
1password-cli = "latest"
watchexec = "latest"

[vars]
IMAGE = "ghcr.io/atty303/obsidian-quartz"

[tasks.install]
run = "npm install"
sources = ["package.json", "package-lock.json"]
outputs.auto = true

[tasks.build]
run = "npx quartz build"
depends = "install"

[tasks.serve]
run = "npx quartz build --serve"
depends = "install"

[tasks.serve-local]
run = "npx quartz build --serve -d {{env.HOME}}/.local/state/obsidian/Personal"
depends = "install"

[tasks.deploy]
run = "wrangler deploy"

[tasks."ob:login"]
run = "op run -- sh -c 'ob login --email $OBSIDIAN_SYNC_EMAIL --password $OBSIDIAN_SYNC_PASSWORD --mfa $OBSIDIAN_SYNC_MFA'"
env.OBSIDIAN_SYNC_EMAIL = "op://Service/Obsidian/username"
env.OBSIDIAN_SYNC_PASSWORD = "op://Service/Obsidian/password"
env.OBSIDIAN_SYNC_MFA = "op://Service/Obsidian/TOTP_rax5uo7xmidqyvv5ggewiaynyq?attribute=otp"

[tasks."ob:sync-setup"]
dir = "content"
run = [
    "ob sync-setup --vault 4a537549e8d60a0ff46bd6513cc46293 --device-name obsidian-quartz",
    "ob sync-config --mode mirror-remote",
    "ob sync-config",
]

[tasks."ob:sync"]
dir = "content"
run = """
until ob sync; do
   sleep 1
done
"""

[tasks."container:build"]
run = "podman build -t {{vars.IMAGE}} . -f publish/Containerfile"

[tasks."container:push"]
run = "podman push {{vars.IMAGE}}"

[tasks."container:run"]
run = "podman run --rm -it -e OP_SERVICE_ACCOUNT_TOKEN -e OBSIDIAN_SYNC_EMAIL -e OBSIDIAN_SYNC_PASSWORD -e CLOUDFLARE_API_TOKEN {{vars.IMAGE}}"

[tasks."container:entrypoint"]
run = [
    "mise run ob:login",
    "mise run ob:sync-setup",
    "mise run container:exec",
]

[tasks."container:exec"]
run = """
exec ${ENTRY_SCRIPT:-./publish/sync-build.sh} --watch 'cd content && until ob sync --continuous; do sleep 1; done' --action 'npx quartz build && wrangler deploy'
"""

[tasks.butane]
run = "podman run --interactive --rm quay.io/coreos/butane:release --pretty --strict < obsidian-quartz.bu > obsidian-quartz.ign"
